#!/bin/bash
# Set hostname
if [ -z $1 ]; then
    echo "No hostname provided"
    exit
fi
sudo hostnamectl hostname $1

sudo flatpak remote-modify --enable flathub
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Copy system config files
sudo rsync -rv ./system/ /

# Enable systemd services
# This assumes /etc/rpm-ostreed.conf has been updated (which it should have been when config files were copied)
sudo rpm-ostree reload
sudo systemctl enable rpm-ostreed-automatic.timer --now
sudo systemctl enable sshd

# Add udev rules for steam
git clone https://github.com/ValveSoftware/steam-devices /tmp/steam-devices
sudo cp /tmp/steam-devices/*.rules /etc/udev/rules.d/.
rm -rf /tmp/steam-devices

